### ISSUE TITLE
How to run this tool

### ISSUE THREAD

**Issue by maskerJT** [mateus558/PLY-models-viewer#1]
hello, I'm looking for some way  to view the 3D .ply files, and your codes seems to be neat and i want to try it, but how to use it?
sincerely thank you

**Comment by mateuscmarim** [comment]
I'll describe the steps in the README.
You're welcome to report any problem that you have.
And thanks for using my code. :)

**Comment by mateuscmarim** [comment]
I've updated the README with the required steps.
Please, give me the feedback if everything goes as expected.
